//mock data

const profile = {
  id: 'profile-current',
  userId: 'current-user',
  name: 'Alex Rivera',
  bio: 'Founder & Full-Stack Engineer | Building tools for the next generation of makers. Open to co-founders and collaborators.',
  avatar: '/home.jpg',
  skills: ['React', 'TypeScript', 'Node.js', 'Product Strategy', 'AI/ML', 'System Design'],
  socials: {
    github: 'https://github.com/alexrivera',
    linkedin: 'https://linkedin.com/in/alexrivera',
    twitter: 'https://twitter.com/alexrivera_dev',
  },
  stats: {
    projects: 5,
    posts: 18,
    collaborations: 7,
  },
};

// feed data

const feed = [
  {
    id: 'feed-1',
    user: { id: 'user-1', name: 'Sarah Kim', avatar: '/home.jpg', rating: '4.9' },
    date: '2026-04-11T08:30:00.000Z',
    caption: 'Launched our AI mentor platform for early-stage founders',
    description: 'After 6 months of building, we just pushed v1 to production. It matches founders with AI-guided mentorship paths based on their stage and vertical. Looking for a growth engineer to join for equity.',
    likes: 142,
    comments: 38,
    shares: 21,
    tags: ['AI', 'Founders', 'Launch'],
  },
  {
    id: 'feed-2',
    user: { id: 'user-2', name: 'Marcus Chen', avatar: '/home.jpg', rating: '4.7' },
    date: '2026-04-10T14:15:00.000Z',
    caption: 'Why we pivoted from B2C to B2B SaaS (and tripled revenue)',
    description: 'We spent 8 months chasing consumer downloads with no monetization. One enterprise pilot changed everything.',
    likes: 98,
    comments: 27,
    shares: 44,
    tags: ['SaaS', 'Pivot', 'B2B', 'Lessons'],
  },
  {
    id: 'feed-3',
    user: { id: 'user-3', name: 'Priya Nair', avatar: '/home.jpg', rating: '4.8' },
    date: '2026-04-10T09:00:00.000Z',
    caption: 'Open-sourced our design system built for fast-moving startups',
    description: 'We extracted our internal component library into NxtUI. Zero config, accessible by default, works with Tailwind.',
    likes: 215,
    comments: 61,
    shares: 87,
    tags: ['Open Source', 'Design System', 'React'],
  },
  {
    id: 'feed-4',
    user: { id: 'current-user', name: 'Alex Rivera', avatar: '/home.jpg', rating: '4.6' },
    date: '2026-04-09T18:45:00.000Z',
    caption: 'Shipped the task engine for MakerSpace',
    description: 'Real-time task assignment, priority queuing, and team-scoped boards are live. Built on Firestore with optimistic UI in Next.js.',
    likes: 74,
    comments: 19,
    shares: 12,
    tags: ['MakerSpace', 'Shipping', 'Firestore'],
  },
  {
    id: 'feed-5',
    user: { id: 'user-4', name: 'Jordan Wells', avatar: '/home.jpg', rating: '4.5' },
    date: '2026-04-08T11:20:00.000Z',
    caption: 'Seeking a technical co-founder for my fintech idea',
    description: 'Strong background in finance and compliance. Looking for someone who can build React Native + Node.js. The problem is real, the TAM is massive, and I have early LOIs.',
    likes: 53,
    comments: 44,
    shares: 9,
    tags: ['CoFounder', 'Fintech', 'Hiring'],
  },
  {
    id: 'feed-6',
    user: { id: 'user-5', name: 'Leila Hassan', avatar: '/home.jpg', rating: '4.9' },
    date: '2026-04-07T16:00:00.000Z',
    caption: '$250k pre-seed raised — here is our deck structure',
    description: 'We closed our pre-seed from 3 angels in 6 weeks. Sharing the exact 12-slide deck structure that worked. No fancy design, just clear narrative and traction proof.',
    likes: 388,
    comments: 92,
    shares: 156,
    tags: ['Fundraising', 'Pre-seed', 'Angels'],
  },
  {
    id: 'feed-7',
    user: { id: 'user-2', name: 'Marcus Chen', avatar: '/home.jpg', rating: '4.7' },
    date: '2026-04-06T10:30:00.000Z',
    caption: 'How we cut our AWS bill by 60% without sacrificing performance',
    description: 'Moved from EC2 to Lambda + Fargate, adopted S3 Intelligent Tiering, and killed 14 zombie resources.',
    likes: 167,
    comments: 48,
    shares: 73,
    tags: ['AWS', 'DevOps', 'Cost Optimization'],
  },
  {
    id: 'feed-8',
    user: { id: 'user-6', name: 'Tom Nakamura', avatar: '/home.jpg', rating: '4.4' },
    date: '2026-04-05T13:00:00.000Z',
    caption: 'My weekend project became my main product',
    description: 'I built a Notion-to-landing-page tool in 48 hours for fun. Posted it on Product Hunt, got 800 upvotes and 8 paying customers by Monday morning.',
    likes: 291,
    comments: 77,
    shares: 102,
    tags: ['IndieHacker', 'Product Hunt', 'Side Project'],
  },
  {
    id: 'feed-9',
    user: { id: 'user-3', name: 'Priya Nair', avatar: '/home.jpg', rating: '4.8' },
    date: '2026-04-04T08:00:00.000Z',
    caption: 'Advice I wish I had before building our first API',
    description: 'Rate limiting, versioning, auth middleware, and documentation are not optional. Sharing the checklist we now use for every new endpoint.',
    likes: 204,
    comments: 55,
    shares: 89,
    tags: ['API', 'Backend', 'Best Practices'],
  },
];

//posts

const posts = [
  {
    id: 'post-1',
    userId: 'current-user',
    content: 'Shipped our MVP landing page today. Took exactly 3 days from wireframe to live. Next step: 50 user interviews before touching the product again.',
    likes: 34,
    comments: 11,
    date: '2026-04-08T09:00:00.000Z',
  },
  {
    id: 'post-2',
    userId: 'current-user',
    content: 'Lesson from this week: scope creep kills speed. We defined 3 core features and shipped every single one. Feels incredible to close a sprint clean.',
    likes: 47,
    comments: 8,
    date: '2026-04-05T15:30:00.000Z',
  },
  {
    id: 'post-3',
    userId: 'current-user',
    content: 'Just integrated AI-powered project matching into MakerSpace. The model scores compatibility based on skills, availability, and project stage. Early results: 84% match acceptance rate in testing.',
    likes: 62,
    comments: 23,
    date: '2026-04-01T11:00:00.000Z',
    image: '/home.jpg',
  },
  {
    id: 'post-4',
    userId: 'current-user',
    content: 'Hot take: most founders build too much before talking to customers. The best MVPs I have seen are glorified spreadsheets and Notion docs.',
    likes: 88,
    comments: 31,
    date: '2026-03-28T17:00:00.000Z',
  },
  {
    id: 'post-5',
    userId: 'current-user',
    content: 'We hit 200 registered makers on NxtGen this week. Small number, but every single one came through word of mouth. Community-led growth is real.',
    likes: 113,
    comments: 42,
    date: '2026-03-21T10:00:00.000Z',
    image: '/home.jpg',
  },
  {
    id: 'post-6',
    userId: 'current-user',
    content: 'Tech stack decision for MakerSpace backend: staying with Node.js + Express + Firestore. Considered Supabase but the migration cost did not justify it at our current scale.',
    likes: 29,
    comments: 14,
    date: '2026-03-15T14:00:00.000Z',
  },
];

// projects

const projects = [
  {
    id: 'proj-1',
    slug: 'makerspace-platform',
    title: 'MakerSpace Platform',
    description: 'A community platform for early-stage founders and builders to collaborate, recruit, and showcase their work. Features real-time messaging, project boards, and AI-powered matching.',
    image: '/home.jpg',
    tags: ['Next.js', 'Node.js', 'Firestore', 'AI'],
    ownerId: 'current-user',
    collaborators: ['user-1', 'user-3'],
    status: 'active',
    createdAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: 'proj-2',
    slug: 'founder-crm',
    title: 'Founder CRM',
    description: 'A lightweight CRM built for founders to track investor conversations, user interviews, and partnership outreach. Integrates with Gmail and Notion.',
    image: '/home.jpg',
    tags: ['React', 'TypeScript', 'PostgreSQL'],
    ownerId: 'current-user',
    collaborators: ['user-2'],
    status: 'completed',
    createdAt: '2025-09-01T00:00:00.000Z',
  },
  {
    id: 'proj-3',
    slug: 'nxtui-design-system',
    title: 'NxtUI Design System',
    description: 'An open-source React component library tailored for fast-moving startups. Accessible by default, Tailwind-compatible, and tree-shakeable.',
    image: '/home.jpg',
    tags: ['React', 'Tailwind', 'Storybook', 'Open Source'],
    ownerId: 'user-3',
    collaborators: ['current-user', 'user-1', 'user-4'],
    status: 'active',
    createdAt: '2025-11-15T00:00:00.000Z',
  },
  {
    id: 'proj-4',
    slug: 'pitch-ai',
    title: 'PitchAI',
    description: 'An AI copilot that helps founders refine their pitch decks using real investor feedback patterns. Analyzes narrative clarity, market sizing, and competitive moat.',
    image: '/home.jpg',
    tags: ['AI', 'GPT-4', 'Python', 'FastAPI'],
    ownerId: 'user-5',
    collaborators: ['user-2'],
    status: 'seeking',
    createdAt: '2026-02-20T00:00:00.000Z',
  },
  {
    id: 'proj-5',
    slug: 'devledger',
    title: 'DevLedger',
    description: 'A blockchain-based contribution ledger for open-source projects. Timestamps and verifies commits on-chain to create a trustless developer reputation score.',
    image: '/home.jpg',
    tags: ['Web3', 'Ethereum', 'Node.js', 'Open Source'],
    ownerId: 'user-6',
    collaborators: [],
    status: 'seeking',
    createdAt: '2026-03-05T00:00:00.000Z',
  },
  {
    id: 'proj-6',
    slug: 'launchweek',
    title: 'LaunchWeek',
    description: 'A structured 7-day accountability sprint tool for indie hackers. Daily check-ins, public commitment threads, and a leaderboard to gamify shipping.',
    image: '/home.jpg',
    tags: ['Next.js', 'Prisma', 'PostgreSQL', 'Gamification'],
    ownerId: 'user-4',
    collaborators: ['user-1', 'current-user'],
    status: 'active',
    createdAt: '2026-02-01T00:00:00.000Z',
  },
];

//tasks

const tasks = [
  {
    id: 'task-1',
    title: 'Draft investor one-pager',
    description: 'Summarize traction metrics, runway, and ask. Format for angels and micro-VCs.',
    status: 'todo',
    priority: 'high',
    assignedTo: 'current-user',
    teamId: 'team-1',
    createdAt: '2026-04-10T09:00:00.000Z',
  },
  {
    id: 'task-2',
    title: 'Implement onboarding flow',
    description: 'Define and build the first-use activation sequence: profile setup, skill tagging, and first project prompt.',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'current-user',
    teamId: 'team-1',
    createdAt: '2026-04-08T11:00:00.000Z',
  },
  {
    id: 'task-3',
    title: 'Write API documentation',
    description: 'Document all public REST endpoints using OpenAPI 3.0. Include request/response examples for projects, tasks, and messages routes.',
    status: 'in-progress',
    priority: 'medium',
    assignedTo: 'user-1',
    teamId: 'team-1',
    createdAt: '2026-04-07T10:00:00.000Z',
  },
  {
    id: 'task-4',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions to run tests, lint, and deploy to staging on every PR merge.',
    status: 'done',
    priority: 'high',
    assignedTo: 'user-3',
    teamId: 'team-1',
    createdAt: '2026-04-01T08:00:00.000Z',
  },
  {
    id: 'task-5',
    title: 'Design recruit listing card UI',
    description: 'Create a responsive card component for the recruit board. Must show role, skills, equity, and commitment level.',
    status: 'done',
    priority: 'medium',
    assignedTo: 'user-1',
    teamId: 'team-1',
    createdAt: '2026-03-28T14:00:00.000Z',
  },
  {
    id: 'task-6',
    title: 'Integrate Stripe for billing',
    description: 'Set up Stripe Checkout and webhook handlers for the Pro plan. Handle upgrade, downgrade, and cancellation flows.',
    status: 'todo',
    priority: 'medium',
    assignedTo: 'current-user',
    teamId: 'team-1',
    createdAt: '2026-04-11T07:00:00.000Z',
  },
  {
    id: 'task-7',
    title: 'User interview synthesis',
    description: 'Compile notes from 20 user interviews into a structured insight doc. Identify top 3 pain points and rank feature requests.',
    status: 'todo',
    priority: 'low',
    assignedTo: 'user-2',
    teamId: 'team-2',
    createdAt: '2026-04-09T16:00:00.000Z',
  },
  {
    id: 'task-8',
    title: 'Fix notification bell unread count',
    description: 'The unread badge does not decrement after opening the notification panel. Bug traced to Firestore listener not triggering re-render.',
    status: 'in-progress',
    priority: 'high',
    assignedTo: 'current-user',
    teamId: 'team-1',
    createdAt: '2026-04-10T18:00:00.000Z',
  },
];

//teams

const teams = [
  {
    id: 'team-1',
    name: 'MakerSpace Core',
    description: 'The founding team building the MakerSpace platform from zero to one.',
    ownerId: 'current-user',
    members: [
      { userId: 'current-user', role: 'owner', joinedAt: '2026-01-10T00:00:00.000Z' },
      { userId: 'user-1', role: 'engineer', joinedAt: '2026-01-15T00:00:00.000Z' },
      { userId: 'user-3', role: 'designer', joinedAt: '2026-01-20T00:00:00.000Z' },
    ],
    projectId: 'proj-1',
    createdAt: '2026-01-10T00:00:00.000Z',
  },
  {
    id: 'team-2',
    name: 'PitchAI Squad',
    description: 'Cross-functional team building AI-powered pitch deck tooling for founders.',
    ownerId: 'user-5',
    members: [
      { userId: 'user-5', role: 'owner', joinedAt: '2026-02-20T00:00:00.000Z' },
      { userId: 'user-2', role: 'engineer', joinedAt: '2026-02-22T00:00:00.000Z' },
      { userId: 'current-user', role: 'advisor', joinedAt: '2026-03-01T00:00:00.000Z' },
    ],
    projectId: 'proj-4',
    createdAt: '2026-02-20T00:00:00.000Z',
  },
  {
    id: 'team-3',
    name: 'LaunchWeek Crew',
    description: 'A small scrappy team shipping accountability tools for indie hackers.',
    ownerId: 'user-4',
    members: [
      { userId: 'user-4', role: 'owner', joinedAt: '2026-02-01T00:00:00.000Z' },
      { userId: 'user-1', role: 'engineer', joinedAt: '2026-02-05T00:00:00.000Z' },
      { userId: 'current-user', role: 'contributor', joinedAt: '2026-02-10T00:00:00.000Z' },
    ],
    projectId: 'proj-6',
    createdAt: '2026-02-01T00:00:00.000Z',
  },
];

//converstions

const conversations = [
  {
    id: 'conv-1',
    participants: ['current-user', 'user-1'],
    lastMessage: 'Sounds good, I will push the PR tonight.',
    lastMessageTime: '2026-04-11T09:45:00.000Z',
    unreadCount: 2,
  },
  {
    id: 'conv-2',
    participants: ['current-user', 'user-5'],
    lastMessage: 'Can you review the deck before Friday?',
    lastMessageTime: '2026-04-10T17:20:00.000Z',
    unreadCount: 1,
  },
  {
    id: 'conv-3',
    participants: ['current-user', 'user-2'],
    lastMessage: 'We should set up a call this week.',
    lastMessageTime: '2026-04-09T13:00:00.000Z',
    unreadCount: 0,
  },
];

//messages

const messages = [
  {
    id: 'msg-1',
    conversationId: 'conv-1',
    senderId: 'current-user',
    receiverId: 'user-1',
    content: 'Hey Sarah, do you have bandwidth to pick up the API docs task this week?',
    timestamp: '2026-04-11T08:30:00.000Z',
    read: true,
  },
  {
    id: 'msg-2',
    conversationId: 'conv-1',
    senderId: 'user-1',
    receiverId: 'current-user',
    content: 'Yes! I was going to start on it today. Should I use Swagger UI or Redoc?',
    timestamp: '2026-04-11T08:55:00.000Z',
    read: true,
  },
  {
    id: 'msg-3',
    conversationId: 'conv-1',
    senderId: 'current-user',
    receiverId: 'user-1',
    content: 'Let us go with Swagger UI — it is already in the repo. I will link the config file.',
    timestamp: '2026-04-11T09:10:00.000Z',
    read: true,
  },
  {
    id: 'msg-4',
    conversationId: 'conv-1',
    senderId: 'user-1',
    receiverId: 'current-user',
    content: 'Got it. What is the base URL for staging?',
    timestamp: '2026-04-11T09:30:00.000Z',
    read: false,
  },
  {
    id: 'msg-5',
    conversationId: 'conv-1',
    senderId: 'user-1',
    receiverId: 'current-user',
    content: 'Sounds good, I will push the PR tonight.',
    timestamp: '2026-04-11T09:45:00.000Z',
    read: false,
  },
  {
    id: 'msg-6',
    conversationId: 'conv-2',
    senderId: 'user-5',
    receiverId: 'current-user',
    content: 'Hey Alex! Loved your post about the task engine. Have you considered adding a Kanban view?',
    timestamp: '2026-04-10T15:00:00.000Z',
    read: true,
  },
  {
    id: 'msg-7',
    conversationId: 'conv-2',
    senderId: 'current-user',
    receiverId: 'user-5',
    content: 'It is on the roadmap for Q2! Right now I am focused on getting the list view stable first.',
    timestamp: '2026-04-10T15:45:00.000Z',
    read: true,
  },
  {
    id: 'msg-8',
    conversationId: 'conv-2',
    senderId: 'user-5',
    receiverId: 'current-user',
    content: 'Makes sense. Also — can you review the deck before Friday?',
    timestamp: '2026-04-10T17:20:00.000Z',
    read: false,
  },
  {
    id: 'msg-9',
    conversationId: 'conv-3',
    senderId: 'current-user',
    receiverId: 'user-2',
    content: 'Marcus, your AWS cost post was gold. We are going through the same thing right now.',
    timestamp: '2026-04-09T11:00:00.000Z',
    read: true,
  },
  {
    id: 'msg-10',
    conversationId: 'conv-3',
    senderId: 'user-2',
    receiverId: 'current-user',
    content: 'Happy to help! The biggest wins were Lambda + killing idle EC2s. What stack are you on?',
    timestamp: '2026-04-09T11:30:00.000Z',
    read: true,
  },
  {
    id: 'msg-11',
    conversationId: 'conv-3',
    senderId: 'current-user',
    receiverId: 'user-2',
    content: 'Mostly Express on a single EC2 right now. Not ideal I know.',
    timestamp: '2026-04-09T12:00:00.000Z',
    read: true,
  },
  {
    id: 'msg-12',
    conversationId: 'conv-3',
    senderId: 'user-2',
    receiverId: 'current-user',
    content: 'We should set up a call this week.',
    timestamp: '2026-04-09T13:00:00.000Z',
    read: true,
  },
];

// notificaitons

const notifications = [
  {
    id: 'notif-1',
    userId: 'current-user',
    type: 'invite',
    message: 'Leila Hassan invited you to collaborate on PitchAI.',
    read: false,
    createdAt: '2026-04-11T07:00:00.000Z',
    actionUrl: '/projects/pitch-ai',
  },
  {
    id: 'notif-2',
    userId: 'current-user',
    type: 'like',
    message: 'Marcus Chen liked your post about the task engine.',
    read: false,
    createdAt: '2026-04-11T06:30:00.000Z',
    actionUrl: '/profile/posts',
  },
  {
    id: 'notif-3',
    userId: 'current-user',
    type: 'comment',
    message: 'Priya Nair commented on your post: "Nice work on the real-time sync!"',
    read: false,
    createdAt: '2026-04-10T21:00:00.000Z',
    actionUrl: '/profile/posts',
  },
  {
    id: 'notif-4',
    userId: 'current-user',
    type: 'recruit',
    message: 'Your profile matched a Full-Stack Engineer listing on LaunchWeek.',
    read: false,
    createdAt: '2026-04-10T16:00:00.000Z',
    actionUrl: '/recruit',
  },
  {
    id: 'notif-5',
    userId: 'current-user',
    type: 'mention',
    message: 'Jordan Wells mentioned you in a post about co-founder matching.',
    read: true,
    createdAt: '2026-04-09T14:00:00.000Z',
    actionUrl: '/explore',
  },
  {
    id: 'notif-6',
    userId: 'current-user',
    type: 'like',
    message: 'Tom Nakamura and 12 others liked your post about community-led growth.',
    read: true,
    createdAt: '2026-04-08T10:00:00.000Z',
    actionUrl: '/profile/posts',
  },
  {
    id: 'notif-7',
    userId: 'current-user',
    type: 'invite',
    message: 'Sarah Kim added you to the MakerSpace Core team.',
    read: true,
    createdAt: '2026-04-07T09:00:00.000Z',
    actionUrl: '/team',
  },
  {
    id: 'notif-8',
    userId: 'current-user',
    type: 'comment',
    message: 'Jordan Wells replied to your comment: "Totally agree on the MVP strategy."',
    read: true,
    createdAt: '2026-04-06T18:00:00.000Z',
    actionUrl: '/explore',
  },
  {
    id: 'notif-9',
    userId: 'current-user',
    type: 'recruit',
    message: 'DevLedger is looking for a Node.js engineer — your profile is a strong match.',
    read: true,
    createdAt: '2026-04-05T12:00:00.000Z',
    actionUrl: '/recruit',
  },
];

// recruit

const recruitListings = [
  {
    id: 'recruit-1',
    title: 'Full-Stack Engineer',
    projectId: 'proj-1',
    projectName: 'MakerSpace Platform',
    skills: ['React', 'Node.js', 'TypeScript', 'Firestore'],
    commitment: 'Part-time (15-20 hrs/week)',
    equity: '0.5-1.5%',
    description: 'We are looking for a full-stack engineer to help scale MakerSpace. You will own features end-to-end from UI to API. Remote-first, async-friendly team.',
    postedBy: 'current-user',
    createdAt: '2026-04-05T00:00:00.000Z',
  },
  {
    id: 'recruit-2',
    title: 'AI/ML Engineer',
    projectId: 'proj-4',
    projectName: 'PitchAI',
    skills: ['Python', 'LangChain', 'OpenAI API', 'FastAPI'],
    commitment: 'Full-time',
    equity: '2-4%',
    description: 'PitchAI is hiring an AI engineer to own the inference pipeline and fine-tuning workflow. Work directly with the founder to shape the product roadmap.',
    postedBy: 'user-5',
    createdAt: '2026-04-03T00:00:00.000Z',
  },
  {
    id: 'recruit-3',
    title: 'Technical Co-Founder',
    projectId: 'proj-5',
    projectName: 'DevLedger',
    skills: ['Solidity', 'Ethereum', 'Node.js', 'Smart Contracts'],
    commitment: 'Full-time',
    equity: '25-35%',
    description: 'Looking for a technical co-founder with Web3 experience to build DevLedger from the ground up. Early-stage with strong open-source traction.',
    postedBy: 'user-6',
    createdAt: '2026-04-01T00:00:00.000Z',
  },
  {
    id: 'recruit-4',
    title: 'Growth & Marketing Lead',
    projectId: 'proj-6',
    projectName: 'LaunchWeek',
    skills: ['Content Marketing', 'SEO', 'Community Building', 'Analytics'],
    commitment: 'Part-time (10 hrs/week)',
    equity: '0.25-0.5%',
    description: 'LaunchWeek has organic traction but needs a growth operator to systematize acquisition. Own the newsletter, run experiments, and grow the community.',
    postedBy: 'user-4',
    createdAt: '2026-03-25T00:00:00.000Z',
  },
];

//investor mock

const investors = [
  {
    id: 'inv-1',
    name: 'Ava Thornton',
    bio: 'Partner at Northgate Ventures. Former founder (2 exits). Focused on developer tools and community-led SaaS. Pro-founder, board seat optional.',
    avatar: '/home.jpg',
    focusAreas: ['Developer Tools', 'SaaS', 'Community Platforms'],
    stage: 'seed',
    portfolio: ['NxtGen', 'CodePilot', 'StackFlow'],
    contactUrl: 'https://northgate.vc/ava',
  },
  {
    id: 'inv-2',
    name: 'Raj Patel',
    bio: 'Angel investor and ex-Google PM. Writes $25k-$100k checks at pre-seed. Loves technical founders with strong distribution instincts.',
    avatar: '/home.jpg',
    focusAreas: ['AI/ML', 'Productivity', 'No-Code'],
    stage: 'pre-seed',
    portfolio: ['PitchAI', 'FormFlow', 'Briefd'],
    contactUrl: 'https://angel.co/rajpatel',
  },
  {
    id: 'inv-3',
    name: 'Clara Mendez',
    bio: 'General Partner at Meridian Fund. Previously VC at a16z. Invests in infrastructure, Web3, and open-source monetization plays.',
    avatar: '/home.jpg',
    focusAreas: ['Web3', 'Open Source', 'Infrastructure'],
    stage: 'series-a',
    portfolio: ['DevLedger', 'OpenStack Pro', 'ChainForge'],
    contactUrl: 'https://meridianfund.io/clara',
  },
  {
    id: 'inv-4',
    name: 'Derek Li',
    bio: 'Solo GP at Microwave Capital. Backed 40+ pre-seed rounds. Big believer in indie hackers going company. Fast decisions, no committee.',
    avatar: '/home.jpg',
    focusAreas: ['Consumer Apps', 'Micro-SaaS', 'EdTech'],
    stage: 'pre-seed',
    portfolio: ['LaunchWeek', 'SkillSnap', 'ReadMe Now'],
    contactUrl: 'https://microwave.capital',
  },
];

//history

const history = [
  {
    id: 'hist-1',
    userId: 'current-user',
    projectId: 'proj-1',
    title: 'MakerSpace idea validated',
    description: 'Ran 20 problem interviews with founders and builders. Clear consensus: discovering collaborators and managing projects in one place is a genuine pain point. Decided to build.',
    type: 'milestone',
    date: '2025-12-01T00:00:00.000Z',
  },
  {
    id: 'hist-2',
    userId: 'current-user',
    projectId: 'proj-2',
    title: 'Founder CRM shipped to 10 beta users',
    description: 'First external users onboarded. Immediate feedback: they want Gmail sync. Added to roadmap within 48 hours and shipped a basic version in 2 weeks.',
    type: 'ship',
    date: '2025-09-15T00:00:00.000Z',
  },
  {
    id: 'hist-3',
    userId: 'current-user',
    projectId: 'proj-1',
    title: 'Pivoted from tool to community platform',
    description: 'Originally scoped as a project management tool. Realized the real moat is the network of makers. Rebuilt the product vision around community, discovery, and collaboration.',
    type: 'pivot',
    date: '2026-01-05T00:00:00.000Z',
  },
  {
    id: 'hist-4',
    userId: 'current-user',
    projectId: 'proj-1',
    title: 'Hit 200 registered makers',
    description: 'Passed the 200 user milestone with zero paid acquisition. All growth came from community posts and maker word-of-mouth. Validated the content-led growth hypothesis.',
    type: 'milestone',
    date: '2026-03-21T00:00:00.000Z',
  },
  {
    id: 'hist-5',
    userId: 'current-user',
    projectId: 'proj-1',
    title: 'Q1 2026 retrospective',
    description: 'Shipped: onboarding, task engine, recruit board, messaging MVP. Did not ship: billing, Kanban view, mobile app. Key lesson: teams of 3 can ship 4 features per quarter sustainably.',
    type: 'retrospective',
    date: '2026-04-01T00:00:00.000Z',
  },
  {
    id: 'hist-6',
    userId: 'current-user',
    projectId: 'proj-3',
    title: 'NxtUI v1.0 open-sourced',
    description: 'Extracted the internal component library into a public package. Published to npm with 23 components, full Storybook docs, and Tailwind integration. 150 GitHub stars in first week.',
    type: 'ship',
    date: '2026-02-14T00:00:00.000Z',
  },
];


module.exports = {
  feed,
  posts,
  profile,
  projects,
  tasks,
  teams,
  messages,
  conversations,
  notifications,
  recruitListings,
  investors,
  history,
};
